### ISSUE TITLE
Maven build fails when source path contains a space

### ISSUE THREAD

**Issue by BryanMorgan** [perfectsense/dari#1]
In working through the default Dari installation instructions I ran into an issue where the Maven compile phase fails with the error below. I think the ClassFinder has a difficult time dealing with paths that contain spaces. This is easily replicated by following the Dari installation steps and trying to install into a path like:

/psd/**Dari Test**/MyProject

By simply removing the space from the path:

/psd/**DariTest**/MyProject

the installation instructions work perfectly. Here's the maven output when the build fails:

Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:572)
    at java.lang.StringBuilder.append(StringBuilder.java:203)
    at java.io.UnixFileSystem.resolve(UnixFileSystem.java:93)
    at java.io.File.<init>(File.java:207)
    at java.io.File.listFiles(File.java:1056)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:144)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)
    at com.psddev.dari.util.ClassFinder.processFile(ClassFinder.java:145)

**Comment by rhino88** [comment]
Closing this issue, the documentation has been updated.
