### ISSUE TITLE
Using Iterables<T> obtained from Query.iterable(Y) causing "java.sql.SQLException: Operation not allowed after ResultSet closed"

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/dari#109]
I am iterating over a huge list of items and then performing manipulations on it, that could change the object.

So, here is what I am doing,

```
Iterable<T> candidates = Query.from(T.class).iterable(100);

for (T current : candidates) {
   current.setVariable("blah");
   
   //At leater point of time

   Another function call which modifies **current** but it fetches the object again using Query call.
   This is because this process is made up of independent components & I need to re-fetch
   the same object again using Query.
}
```

This seems to throw the following error,
```
com.psddev.dari.db.SqlDatabaseException: java.sql.SQLException: Operation not allowed after ResultSet closed (SELECT DISTINCT r.`id`, r.`typeId`, r.`data`
FROM `Record` r /*! IGNORE INDEX (PRIMARY) */
INNER JOIN `RecordString4` i0 ON i0.`id` = r.`id` AND i0.`typeId` = r.`typeId` AND i0.`symbolId` IN (1536)
WHERE 1 = 1
AND r.`typeId` IN (X'00000148858edd9fad4da7aea4c60000')
AND (i0.`symbolId` = 1536 AND i0.`value` IS NOT NULL AND (i0.`value` = X'636f6d706c65746564' OR  i0.`value` = X'7061796d656e745f68616e646c65725f6973737565')))
	at com.psddev.dari.db.SqlDatabase.createQueryException(SqlDatabase.java:187)
	at com.psddev.dari.db.SqlDatabase.access$300(SqlDatabase.java:66)
	at com.psddev.dari.db.SqlDatabase$SqlIterator.next(SqlDatabase.java:1205)
	at com.snagfilms.jobs.JobSpecial.doTask(JobSpecial.java:185)
	at com.psddev.dari.util.Task.run(Task.java:451)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1084)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:799)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:847)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4877)
	at com.psddev.dari.db.SqlDatabase.createSavedObjectWithResultSet(SqlDatabase.java:805)
	at com.psddev.dari.db.SqlDatabase.access$600(SqlDatabase.java:66)
	at com.psddev.dari.db.SqlDatabase$SqlIterator.next(SqlDatabase.java:1199)
	... 7 more
```

 Can you tell me what's actually happening & how to resolve this?

**Comment by hyoolim** [comment]
I'm closing this issue for now, as there hasn't been any activity in some time, but if you're still having problems, please feel free to reopen.

Going forward, we'll be more closely monitoring the issues here so that the questions don't go unanswered for so long.
