### ISSUE TITLE
While Using Code tool and testing any code getting error

### ISSUE THREAD

**Issue by sachinkaushik** [perfectsense/dari#267]
Hi @rhino88 ,

While I'm using **Code Tool of DariFramework** and testing code on it getting below error.

java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.psddev.dari.util.CodeDebugServlet$2.<init>(CodeDebugServlet.java:93)
	at com.psddev.dari.util.CodeDebugServlet.doSave(CodeDebugServlet.java:91)
	at com.psddev.dari.util.CodeDebugServlet.service(CodeDebugServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at com.psddev.dari.util.DebugFilter$ServletWrapper.serviceServlet(DebugFilter.java:690)
	at com.psddev.dari.util.DebugFilter.doRequest(DebugFilter.java:274)
	at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:420)
	at com.psddev.dari.util.DebugFilter.doDispatch(DebugFilter.java:171)
	at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:582)
	at com.psddev.dari.util.ResourceFilter.doRequest(ResourceFilter.java:64)
	at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:420)
	at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:582)
	at com.psddev.dari.util.AbstractFilter.doFilter(AbstractFilter.java:292)
	at com.psddev.dari.util.AbstractFilter$DependencyFilterChain.doFilter(AbstractFilter.java:575)
	at com.psddev.dari.util.DebugFilter$SettingsOverrideFilter.doRequest(DebugFilter.java:752)
	at com.psddev.dari.util.AbstractFilter.doDispatch(AbstractFilter.java:420)

Please check below code.
**import com.bs.User;
import com.psddev.dari.db.*;
import com.psddev.dari.util.*;
import java.util.*;

public class Code {
    public static Object main() throws Throwable {
            
      return Movie.class;
        
    }
}**

**Comment by dev-support** [comment]
@sachinkaushik, this was not something reproducible on our side. Is this still occurring to you? Might be something unique to your local implementation.
