### ISSUE TITLE
sortAscending when using path notation

### ISSUE THREAD

**Issue by andypearson** [perfectsense/dari#90]
When using `sortAscending` with path notation we are seeing a `JdbcSQLException`.

Using the following query:

    List<Event> events = Query.from(Event.class)
        .where("location != missing")
        .and("location/shortTitle != missing")
        .and("eventType = ?", types)
        .and("date >= ?", new Date())
        .sortAscending("location/shortTitle")
        .selectAll();

We receive the following SQL error:

    Caused by: org.h2.jdbc.JdbcSQLException: Order by expression "S0I0.VALUE" must be in the result list in this case; SQL statement:
    SELECT DISTINCT r.id, r.typeId, r.data
    FROM Record r
    INNER JOIN RecordUuid3 i0 ON i0.id = r.id AND i0.typeId = r.typeId AND i0.symbolId IN (15)
    INNER JOIN RecordString4 i1 ON i1.id = r.id AND i1.typeId = r.typeId AND i1.symbolId IN (14)
    INNER JOIN RecordNumber3 i2 ON i2.id = r.id AND i2.typeId = r.typeId AND i2.symbolId IN (16)
    INNER JOIN Record s0r ON i0.value = s0r.id
    LEFT OUTER JOIN RecordString4 s0i0 ON s0i0.id = s0r.id AND s0i0.typeId = s0r.typeId AND s0i0.symbolId IN (7)
    WHERE 1 = 1
    AND r.typeId IN ('0000014e-4a73-d7f8-a95e-eaf7b9610008')
    AND ((i0.value IS NOT NULL)
    AND (i0.value NOT IN (SELECT DISTINCT r.id
    FROM Record r
    LEFT OUTER JOIN RecordString4 i0 ON i0.id = r.id AND i0.typeId = r.typeId AND i0.symbolId IN (7, 7, 7)
    WHERE 1 = 1
    AND ((i0.value IS NOT NULL)
    OR (i0.value IS NOT NULL)
    OR (i0.value IS NOT NULL))))
    AND (i1.symbolId = 14 AND i1.value IS NOT NULL AND i1.value = X'6f70656e6576656e74')
    AND (i2.symbolId = 16 AND i2.value IS NOT NULL AND i2.value >= 1435768183705))
    ORDER BY  s0i0.value DESC [90068-187]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.dml.Query.initOrder(Query.java:433)
        at org.h2.command.dml.Select.init(Select.java:788)
        at org.h2.command.Parser.parseSelect(Parser.java:1683)
        at org.h2.command.Parser.parsePrepared(Parser.java:433)
        at org.h2.command.Parser.parse(Parser.java:305)
        at org.h2.command.Parser.parse(Parser.java:277)
        at org.h2.command.Parser.prepareCommand(Parser.java:242)
        at org.h2.engine.Session.prepareLocal(Session.java:461)
        at org.h2.engine.Session.prepareCommand(Session.java:403)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
        at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:73)
        at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:503)
        at com.psddev.dari.db.SqlDatabase.executeQueryBeforeTimeout(SqlDatabase.java:1061)
        at com.psddev.dari.db.SqlDatabase.selectListWithOptions(SqlDatabase.java:1330)

Is this use case supported? What is the alternative?

**Comment by Ryan-Anderson** [comment]
Hi Andy,

This is a bug in the current h2 implementation, we are working on fixing this issue here: [feature/jooq](https://github.com/perfectsense/dari/tree/feature/jooq).

**Comment by andypearson** [comment]
Thanks for the update on this Ryan, do you know when we can expect a fix?

**Comment by Ryan-Anderson** [comment]
No ETA yet. We are looking to couple that feature with a comprehensive set of unit tests for SqlQuery.
